import { StyleSheet } from 'react-native';
import { Colors, Spacing, BorderRadius, FontSizes } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: Spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  card: {
    backgroundColor: Colors.background,
    borderRadius: BorderRadius.large,
    padding: Spacing.xxxl,
    maxWidth: 600,
    width: '100%',
    alignItems: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 12,
    borderWidth: 4,
    borderColor: Colors.yellow,
  },
  primaryButton: {
    backgroundColor: Colors.teal,
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: BorderRadius.md,
    marginBottom: Spacing.md,
    minWidth: 250,
    borderWidth: 2,
    borderColor: Colors.tealDark,
  },
  primaryButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  primaryButtonText: {
    color: Colors.white,
    fontSize: FontSizes.md,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  disabledButton: {
    backgroundColor: '#ccc',
  },
  disabledButtonText: {
    color: Colors.darkGray,
  },
  audioContainer: {
    backgroundColor: 'rgba(78, 205, 196, 0.05)',
    padding: Spacing.xl,
    borderRadius: BorderRadius.lg,
    marginBottom: Spacing.md,
    alignItems: 'center',
    borderWidth: 3,
    borderColor: Colors.teal,
    width: '100%',
  },
  microphoneIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(224, 224, 224, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Spacing.lg,
    borderWidth: 4,
    borderColor: '#E0E0E0',
  },
  microphoneIconUser: {
    backgroundColor: 'rgba(78, 205, 196, 0.2)',
    borderColor: Colors.teal,
    transform: [{ scale: 1.1 }],
  },
  microphoneIconAgent: {
    backgroundColor: 'rgba(255, 217, 61, 0.2)',
    borderColor: Colors.yellow,
    transform: [{ scale: 1.1 }],
  },
  speakerLabel: {
    fontSize: FontSizes.lg,
    color: Colors.teal,
    textAlign: 'center',
    fontWeight: '600',
  },
  speakerLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: Spacing.lg,
  },
  helpText: {
    fontSize: FontSizes.sm,
    color: Colors.darkGray,
    textAlign: 'center',
    fontStyle: 'italic',
    marginBottom: Spacing.md,
  },
  endButton: {
    backgroundColor: Colors.coral,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.sm,
    borderWidth: 2,
    borderColor: Colors.coralDark,
  },
  endButtonText: {
    color: Colors.white,
    fontSize: FontSizes.sm,
    fontWeight: 'bold',
  },
  processingContainer: {
    backgroundColor: 'rgba(255, 217, 61, 0.2)',
    padding: Spacing.lg,
    borderRadius: BorderRadius.md,
    marginBottom: Spacing.md,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: Colors.yellow,
  },
  processingText: {
    fontSize: FontSizes.md,
    color: Colors.yellowDark,
    textAlign: 'center',
    fontWeight: '600',
  },
  processingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  testButton: {
    backgroundColor: Colors.yellow,
    paddingHorizontal: 30,
    paddingVertical: 12,
    borderRadius: BorderRadius.md,
    marginBottom: Spacing.sm,
    minWidth: 250,
    borderWidth: 2,
    borderColor: Colors.yellowDark,
  },
  testButtonText: {
    color: '#333',
    fontSize: FontSizes.sm,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
