import { StyleSheet, Platform } from 'react-native';
import { Colors } from '@/constants/theme';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.paper,
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        height: '100%',
    },
    pageWrapper: {
        width: '100%',
        maxWidth: 800,
        height: '100%',
        paddingBottom: 100,
        paddingTop: 20,
        paddingHorizontal: 20,
    },
    scrollContent: {
        flexGrow: 1,
        alignItems: 'center',
        paddingBottom: 40,
    },
    pageNumber: {
        textAlign: 'center',
        color: Colors.gray,
        fontSize: 12,
        marginBottom: 10,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    illustration: {
        width: '100%',
        height: 300,
        borderRadius: 8,
        marginBottom: 20,
        backgroundColor: Colors.lightestGray,
        resizeMode: 'contain',
    },
    shimmerPlaceholder: {
        backgroundColor: Colors.lighterGray,
    },
    storyText: {
        fontSize: 22,
        lineHeight: 34,
        color: Colors.darkestGray,
        fontFamily: Platform.OS === 'web' ? 'Georgia, serif' : 'serif',
        textAlign: 'left',
        width: '100%',
    },
    navigationRow: {
        position: 'absolute',
        bottom: 20,
        left: 20,
        right: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        zIndex: 9998,
    },
    narrationControlsContainer: {
        position: 'absolute',
        bottom: 100,
        right: 20,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 9998,
    },
    navButton: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: Colors.white,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 4,
        borderWidth: 1,
        borderColor: Colors.lightestGray,
    },
    disabledBtn: {
        opacity: 0.3,
        backgroundColor: '#f5f5f5',
    },
    navArrow: {
        fontSize: 32,
        color: Colors.accent,
        marginTop: -4,
        fontWeight: '300',
    },
    dotsContainer: {
        flexDirection: 'row',
        gap: 8,
    },
    dot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: Colors.lighterGray,
    },
    dotActive: {
        backgroundColor: Colors.accent,
        width: 12,
    },
    // END PAGE STYLES
    endPageContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        maxWidth: 400,
        alignSelf: 'center',
        padding: 30,
    },
    endTitle: {
        fontSize: 36,
        fontWeight: 'bold',
        color: Colors.darkestGray,
        marginBottom: 10,
        textAlign: 'center',
    },
    endSubtitle: {
        fontSize: 18,
        color: Colors.darkGray,
        marginBottom: 40,
        textAlign: 'center',
    },
    endButton: {
        width: '100%',
        padding: 18,
        borderRadius: 12,
        marginBottom: 16,
        alignItems: 'center',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    endButtonContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    primaryButton: {
        backgroundColor: Colors.accent,
    },
    primaryButtonText: {
        fontSize: 20,
        fontWeight: '600',
        color: 'white',
    },
    secondaryButton: {
        backgroundColor: Colors.white,
        borderWidth: 2,
        borderColor: Colors.accent,
    },
    secondaryButtonText: {
        fontSize: 18,
        fontWeight: '600',
        color: Colors.accent,
    },
    tertiaryButton: {
        backgroundColor: 'transparent',
    },
    tertiaryButtonText: {
        fontSize: 16,
        color: Colors.darkGray,
    },
    // BACK TO BOOKSHELF BUTTON
    backToBookshelfBtn: {
        position: 'absolute',
        bottom: 100,
        left: 20,
        backgroundColor: `rgba(250, 249, 246, 0.92)`,
        borderRadius: 20,
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderWidth: 1,
        borderColor: '#ddd',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        zIndex: 9998,
    },
    backToBookshelfBtnText: {
        fontSize: 15,
        color: Colors.accent,
        fontWeight: '600',
    },
    storyName: {
        fontSize: 28,
        fontWeight: 'bold',
        color: Colors.darkestGray,
        textAlign: 'center',
        marginBottom: 16,
        fontFamily: Platform.OS === 'web' ? 'Georgia, serif' : 'serif',
    },
    closeButton: {
        position: 'absolute',
        top: 20,
        right: 20,
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'rgba(250, 249, 246, 0.92)',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#ddd',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        zIndex: 9999,
    },
});